[package]
name = "routeros-utils"
version = "0.1.0"
authors = ["Adam Batkin <adam@batkin.net>"]
edition = "2018"

[dependencies]
structopt = "0.3"
prettytable-rs = "0.10"

[dependencies.routeros_rust]
git = "https://github.com/dmvoiper/Mikrotik-rust"
